//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityChatBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Acc> Accs { get; set; }
        public virtual DbSet<addquery> addqueries { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Cabin> Cabins { get; set; }
        public virtual DbSet<classroom> classrooms { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<contactquery> contactqueries { get; set; }
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<doublereply> doublereplies { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<faculaty> faculaties { get; set; }
        public virtual DbSet<generalreply> generalreplies { get; set; }
        public virtual DbSet<Invalid> Invalids { get; set; }
        public virtual DbSet<namequery> namequeries { get; set; }
        public virtual DbSet<Que> Ques { get; set; }
        public virtual DbSet<QuestionPaper> QuestionPapers { get; set; }
        public virtual DbSet<ReferenceBook> ReferenceBooks { get; set; }
        public virtual DbSet<specialization> specializations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<timetable> timetables { get; set; }
        public virtual DbSet<whatdoublereply> whatdoublereplies { get; set; }
        public virtual DbSet<wheredoublereply> wheredoublereplies { get; set; }
        public virtual DbSet<whodoublereply> whodoublereplies { get; set; }
    }
}
