//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class doublereply
    {
        public int doublereplyId { get; set; }
        public string Sr { get; set; }
        public string query1 { get; set; }
        public string query2 { get; set; }
        public string query3 { get; set; }
        public string query4 { get; set; }
        public string keywords { get; set; }
        public string reply { get; set; }
    }
}
