//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class namequery
    {
        public int namequeriesId { get; set; }
        public string query1 { get; set; }
    }
}
