//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityChatBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionPaper
    {
        public int QuestionPapersId { get; set; }
        public string Sr { get; set; }
        public string K1 { get; set; }
        public string K2 { get; set; }
        public string K3 { get; set; }
        public string K4 { get; set; }
        public string K5 { get; set; }
        public string K6 { get; set; }
        public string keywords { get; set; }
        public string Reply { get; set; }
        public string Link { get; set; }
    }
}
